New services for thermostatic analysis
Energy-Sparks/energy-sparks_analytics pull request #398
Opened 2023-01-20 16:52 UTC by iant

2023-01-25 09:46 UTC, ldodds commented on app/services/heating/heating_thermostatic_analysis_service.rb
> +    attr_reader :aggregated_heat_meters
probably don't need this?

2023-01-25 09:52 UTC, ldodds requested changes

2023-01-25 09:52 UTC, ldodds commented on app/services/heating/heating_thermostatic_analysis_service.rb
> +  class HeatingThermostaticAnalysisService
Could this not extend the Heating::BaseService?

Looks like there's some shared behaviour, e.g. creating a model (but need to check whether the way that the `AdviceGasThermostaticControl` and now this class aligns with the model created in the code I wrote.

The `enough_data?` check will also allow the application to test whether we can actually create and run a model.

2023-01-30 17:18 UTC, ldodds commented
Would be too to finish this up @iant. Can you review my comment about extending the base service I added, will help us avoid code duplication around model creation.

Overriding the `enough_data?` check (if necessary) will be part of adding the new Analysable mixin.

2023-01-31 12:00 UTC, iant commented
@ldodds I think this is ready for another review.  heating model seems to differ to the one in the base service so have overridden but we can still use the enough_data and validate_meter_collection methods.

2023-02-01 09:24 UTC, ldodds approved these changes

2023-02-01 09:24 UTC, ldodds commented on app/services/heating/heating_thermostatic_analysis_service.rb
> +    def data_available_from
This isn't correct. The AnalysableMixin data_available_from method should be the date from which the analysis will be available, i.e. when there is sufficient data available, not the date from which we have data.

I've implemented some generic code for this check here:

https://github.com/Energy-Sparks/energy-sparks_analytics/pull/404/files#diff-5ea50f622f59bb6ebe5351661d00cc9f981910fcb0b247b328ff18d717e41ff4R66

And use it here:

https://github.com/Energy-Sparks/energy-sparks_analytics/pull/404/files#diff-9d1273e9c4b66026620637517f4775672860bd2accc3ac42bd8651baefd1a14dR28

2023-02-01 09:24 UTC, ldodds commented on app/services/heating/heating_thermostatic_analysis_service.rb
> +    def data_available_from
Maybe go ahead and merge this, when review these two methods across all services once we've merged my PR.

2023-02-01 17:06 UTC, merged