New service for recent progress
Energy-Sparks/energy-sparks_analytics pull request #402
Opened 2023-01-27 17:15 UTC by iant

2023-01-30 17:58 UTC, ldodds commented on app/services/baseload/baseload_period_comparison_service.rb
> +module Baseload
I think this is the wrong module and class name? 

The recent changes advice page isn't doing any comparisons for baseload, it's looking at overall energy consumption for gas and electricity.

2023-01-30 17:58 UTC, ldodds commented on app/services/baseload/baseload_period_comparison_service.rb
> +        current_period_start_date: current_period_start_date,
These should really be a pair of CombinedUsageMetric, one for the current period, one for the previous. Along with the period start and end date. 

It might be useful to have a Period Comparison class that covers that, we could use that in other places to I think.

2023-02-02 09:24 UTC, iant commented
@ldodds this is ready for a review.  docs
https://docs.google.com/document/d/1y8vGPUutYCkM-uVGkB6BFQhPPMjIq75_8qpxg5OOm_M/edit
https://docs.google.com/document/d/1gYLAVDLOit94k6kZLSJOqZ3D97WJZIoY02SXFATETFE/edit#heading=h.bxsn344l7y99
ratings and an equivalences are missing (difference_co2_smartphone_kwh), which i assume can be done on the application side?

2023-02-07 09:30 UTC, ldodds requested changes

2023-02-07 09:30 UTC, ldodds commented on app/services/usage/combined_usage_metric_comparison_service.rb
> +  class CombinedUsageMetricComparisonService
This isn't a service, its a plain old ruby object?

Can you rename as `CombinedUsageMetricComparison` and move to the `classes` directory?

2023-02-07 09:30 UTC, ldodds commented on app/services/usage/recent_usage_comparison_service.rb
> +    def create_model
maybe `recent_usage` as more descriptive, we're not creating a model here.

2023-02-07 11:26 UTC, iant commented
@ldodds class and method name updated. think this one's ready for another review....

2023-02-07 11:34 UTC, ldodds approved these changes

2023-02-07 11:38 UTC, merged